/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: ArjB (https://sketchfab.com/arjunbalan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-ipad-pro-2020-6c744f3da64247cfb2a0cbfeaf361c87
Title: Apple Ipad Pro 2020
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials } = useGLTF('./3d/ipad/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Plane_13" position={[0, 1.944, 0]} rotation={[Math.PI, 0, Math.PI]} scale={0.155}>
                <group name="Circle_12" position={[-15.94, -0.003, -22.334]} rotation={[0, 0, Math.PI]} scale={1.855}>
                  <group name="Circle001_6" position={[0, -0.004, 0]}>
                    <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
                    <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
                    <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.000']} />
                    <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Material} />
                    <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.008']} />
                  </group>
                  <group name="Cube_10" position={[-8.593, 0.283, 11.824]} rotation={[-Math.PI / 2, 0, 0]} scale={3.476}>
                    <group name="Sphere_7" position={[2.422, 3.397, -0.082]} scale={[0.067, 0.067, 0.022]}>
                      <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.lens} />
                      <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials['sc.000']} />
                    </group>
                    <group name="Sphere001_8" position={[2.452, 2.883, -0.082]} scale={[0.07, 0.07, 0.024]}>
                      <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.lens} />
                      <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['sc.000']} />
                    </group>
                    <group name="Sphere002_9" position={[1.991, 3.144, -0.082]} scale={[0.062, 0.062, 0.021]}>
                      <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.lens} />
                      <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials['sc.000']} />
                    </group>
                    <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material} />
                    <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials['sc.001']} />
                    <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
                    <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.scre} />
                    <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['bod.001']} />
                    <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials['bod.002']} />
                    <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.wirles} />
                  </group>
                  <group name="Cube001_11" position={[-1.533, -0.014, 1.72]} rotation={[-Math.PI, -0.77, -Math.PI]} scale={[0.085, 0.022, 0]}>
                    <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.material_0} />
                  </group>
                  <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material} />
                </group>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
              </group>
              <group name="Cube003_17" position={[2.031, 1.947, 2.969]} rotation={[0, -0.77, Math.PI]} scale={[0.024, 0.006, 0]}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.material_0} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
