/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf 
Author: Niilo Poutanen (https://sketchfab.com/niilo.poutanen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-tv-remote-38f2339bfc974f1e81fe7b1d2b96330a
Title: Apple TV remote
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./3D/tv/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.003]} scale={0.05}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.004, 140.611, 15.8]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Frame_Frame_0.geometry} material={materials.Frame} />
            <mesh geometry={nodes.Frame_Black_plastic_0.geometry} material={materials.Black_plastic} />
            <mesh geometry={nodes.Frame_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Frame_White_plastic_0.geometry} material={materials.White_plastic} />
            <mesh geometry={nodes.Frame_Gold_0.geometry} material={materials.Gold} />
            <mesh geometry={nodes.Frame_Frame_logo_0.geometry} material={materials.Frame_logo} />
            <mesh geometry={nodes.MainButton_Buttons_0.geometry} material={materials.Buttons} position={[0, 0.02, 3.932]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.Buttons_Buttons_0.geometry} material={materials.Buttons} position={[0.753, -0.02, 1.656]} rotation={[Math.PI / 2, 0, 0]} />
            <mesh geometry={nodes.VoiceButton_Frame_logo_0.geometry} material={materials.Frame_logo} position={[1.818, 0.175, 3.936]} rotation={[0, Math.PI / 2, 0]} />
            <mesh geometry={nodes.Power_button_Frame_logo_0.geometry} material={materials.Frame_logo} position={[0.753, -0.02, 1.656]} rotation={[Math.PI / 2, 0, 0]} scale={0.617} />
            <mesh geometry={nodes.BoltRight_Metal_0.geometry} material={materials.Metal} position={[1.296, 0.228, -6.674]} rotation={[Math.PI, 0.601, -Math.PI]} />
            <mesh geometry={nodes.BoltLeft_Metal_0.geometry} material={materials.Metal} position={[-1.292, 0.228, -6.676]} rotation={[Math.PI, -0.003, Math.PI]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
